# Runtime policy helpers for qubes-snitchd
# YAML persistence, in-memory indexes, and nft reloads live here instead of packet callbacks

import copy
import os

from qubes_snitch import config
from qubes_snitch import nft
from qubes_snitch import policy
from qubes_snitch import queue


# Use the config parser's exact Qubes dispNNN/dispNNNN contract so cleanup and source mapping cannot drift
DISPOSABLE_SOURCE_RE = config.NUMBERED_DISPVM_RE
TEMP_DISPVM_HEADER = """# DO NOT EDIT THIS FILE
# This numbered DispVM policy is temporary and is deleted when qubes-snitchd stops or restarts
# Qubes can reuse numbered DispVM names such as disp1234 for unrelated future VMs
# Qubes-Snitch deletes this file on restart to prevent stale disp1234 rules from applying to a later disposable
# For persistent user-edited disposable policy, create/use a purpose-specific DispVM base so Qubes-Snitch can use dispvm-<base>.yml
"""


def load_nft(ctx):
    # Render and atomically load the daemon's current in-memory policy into the private nft table
    nft.load_nft(ctx.NFT_FILE, ctx.SOURCES_BY_NAME, ctx.RULES, ctx.CONFIG, ctx.NFT_TABLE, ctx.QUEUE_NUM)


def load_fail_closed_nft(ctx):
    # Before dom0 source discovery succeeds, install a table with no established/related bypass
    nft.load_fail_closed_nft(ctx.NFT_FILE, ctx.CONFIG, ctx.NFT_TABLE, ctx.QUEUE_NUM)


def ensure_rule_entry(ctx, source):
    # Known sources need an in-memory empty bucket, but YAML is created only after a real user decision
    if source in ctx.RULES:
        return False
    path = ctx.RULES_DIR / f"{source}.yml"
    if path.exists():
        data = config.read_yaml(path)
        config.validate_rule_file(path, data)
        ctx.RULES[source] = {"ip": data["rules4"], "dns": data["dns"]}
    else:
        ctx.RULES[source] = {"ip": [], "dns": []}
    return True



def delete_numbered_dispvm_file(ctx, path):
    # Numbered DispVM names are not durable identities, so stale files are deleted instead of loaded
    if path.exists():
        ctx.syslog.syslog(ctx.syslog.LOG_INFO, f"QUBES-SNITCH delete temporary DispVM rule file {path}")
        path.unlink()


def cleanup_numbered_dispvm_files(ctx):
    # Startup and clean stop remove numbered DispVM policy because Qubes may reuse disp1234 later
    removed = False
    for path in sorted(ctx.RULES_DIR.glob("disp[0-9]*.yml")):
        if not DISPOSABLE_SOURCE_RE.fullmatch(path.stem):
            continue
        delete_numbered_dispvm_file(ctx, path)
        ctx.RULES.pop(path.stem, None)
        removed = True
    return removed


def cleanup_disposable_rule_entries(ctx):
    # When a numbered DispVM disappears, drop its temporary YAML and rebuild nft without its chain
    removed = False
    for source in list(ctx.RULES):
        if source in ctx.SOURCES_BY_NAME or not DISPOSABLE_SOURCE_RE.fullmatch(source):
            continue
        del ctx.RULES[source]
        queue.remove_pending_for_source(source)
        with ctx.DNS_CACHE_LOCK:
            for key in [key for key in ctx.DNS_RESPONSE_CACHE if key[0] == source]:
                del ctx.DNS_RESPONSE_CACHE[key]
            for key in [key for key in ctx.DNS_QNAME_CACHE if key[0] == source]:
                del ctx.DNS_QNAME_CACHE[key]
        delete_numbered_dispvm_file(ctx, ctx.RULES_DIR / f"{source}.yml")
        removed = True
    return removed


def cleanup_reused_numbered_dispvm_entries(ctx, old_sources_by_name):
    # A changed IP for the same numbered name means Qubes reused the disposable before we saw it absent
    removed = False
    for source, old_ips in old_sources_by_name.items():
        if not DISPOSABLE_SOURCE_RE.fullmatch(source):
            continue
        if source not in ctx.SOURCES_BY_NAME or ctx.SOURCES_BY_NAME[source] == old_ips:
            continue
        ctx.RULES.pop(source, None)
        queue.remove_pending_for_source(source)
        with ctx.DNS_CACHE_LOCK:
            for key in [key for key in ctx.DNS_RESPONSE_CACHE if key[0] == source]:
                del ctx.DNS_RESPONSE_CACHE[key]
            for key in [key for key in ctx.DNS_QNAME_CACHE if key[0] == source]:
                del ctx.DNS_QNAME_CACHE[key]
        delete_numbered_dispvm_file(ctx, ctx.RULES_DIR / f"{source}.yml")
        removed = True
    return removed


def prompt_source_current(ctx, request):
    # Stale prompts must not write policy if a source disappeared or changed IP while the CLI waited
    source = request["source"]
    if source not in ctx.SOURCES_BY_NAME:
        return False
    src = request.get("src")
    if src and src not in ctx.SOURCES_BY_NAME[source]:
        return False
    return True


def matching_action(ctx, request):
    # Read policy under the same lock used by CLI saves and QubesDB refreshes to avoid half-updated maps
    with ctx.POLICY_LOCK:
        return policy.matching_action(request, ctx.RULES)


def load_policy_without_sources(ctx):
    # Load local config/rules first; this cannot depend on dom0 qrexec being responsive
    ctx.CONFIG = config.read_config(ctx.CONFIG_FILE)
    cleanup_numbered_dispvm_files(ctx)
    ctx.RULES = config.load_rules(ctx.RULES_DIR, ctx.CONFIG["default_disposable_vm_name"], ctx.CONFIG["dns_cache_refresh_workers"])


def append_rule(ctx, request, action):
    # Numbered DispVM answers are valid only while that exact disposable is still alive
    if DISPOSABLE_SOURCE_RE.fullmatch(request["source"]) and request["source"] not in ctx.SOURCES_BY_NAME:
        raise SystemExit(f"stale numbered DispVM prompt: {request['source']}")
    # Build the new YAML/memory state first; publish to memory only after the persistent file write succeeds
    path = ctx.RULES_DIR / f"{request['source']}.yml"
    if not path.exists():
        data = {"rules4": [], "dns": []}
    else:
        data = config.read_yaml(path)
        config.validate_rule_file(path, data)
    next_rules = copy.deepcopy(ctx.RULES)
    if request.get("kind") == "dns":
        policy.append_dns_rule(request, action, data, next_rules)
    else:
        policy.append_flow_rule(request, action, data, next_rules)
    config.validate_rule_file(path, data)
    tmp_path = path.with_name(path.name + ".tmp")
    prefix = TEMP_DISPVM_HEADER if DISPOSABLE_SOURCE_RE.fullmatch(request["source"]) else ""
    tmp_path.write_text(prefix + ctx.yaml.safe_dump(data, sort_keys=False), encoding="utf-8")
    os.replace(tmp_path, path)
    ctx.RULES = next_rules
    # DNS display hints are refreshed lazily in the CLI thread, not while POLICY_LOCK is held here

